import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Set style for better-looking plots
plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['font.size'] = 19
plt.rcParams['axes.labelsize'] = 21
plt.rcParams['axes.titlesize'] = 22
plt.rcParams['legend.fontsize'] = 19
plt.rcParams['xtick.labelsize'] = 19
plt.rcParams['ytick.labelsize'] = 19

import os
os.makedirs("plots", exist_ok=True)

# Load baselines from CSV (generated by plot_results.sh Step 0)
_baselines = pd.read_csv("csv/baselines.csv").set_index("model")["baseline"]

# Model configurations: (base_name, display_name, baseline)
model_configs = [
    ("resnet",     "ResNet20",     _baselines["resnet"]),
    ("mobilenet",  "MobileNetv2",  _baselines["mobilenet"]),
    ("shufflenet", "ShuffleNetv2", _baselines["shufflenet"]),
    ("yolo",       "YOLOv9",       _baselines["yolo"]),
]
types = ["mult", "bitflip"]   # top, bottom

# Define colors and markers for consistency
colors = {"nvbit": "#2E86AB", "pytorchfi": "#A23B72", "mrfi": "#F18F01"}
markers = {"nvbit": "o", "pytorchfi": "s", "mrfi": "^"}
line_styles = {"nvbit": "-", "pytorchfi": "--", "mrfi": "-."}

fig, axes = plt.subplots(2, 4, figsize=(18, 10))

for col, (model_name, display_name, baseline) in enumerate(model_configs):
    for row, typ in enumerate(types):
        ax = axes[row, col]
        fname = f"csv/{model_name}_{typ}.csv"

        df = pd.read_csv(fname)

        # all CSVs store values in "accuracy" column (mAP@50 for YOLO, % accuracy for others)
        metric = "accuracy" if "accuracy" in df.columns else "map50"

        for method in ["nvbit", "pytorchfi", "mrfi"]:
            sub = df[df["method"] == method].sort_values("count")
            # Map method names for display
            display_label = "TensorDynamic" if method == "nvbit" else method.upper()
            ax.plot(sub["count"], sub[metric],
                   marker=markers[method],
                   color=colors[method],
                   linestyle=line_styles[method],
                   label=display_label,
                   linewidth=2.5,
                   markersize=7,
                   alpha=0.9)

        # Add baseline horizontal line
        ax.axhline(y=baseline, color='red', linestyle=':', linewidth=2,
                   label='Baseline (Error-Free)', alpha=0.7)

        ax.set_xscale("log")

        # Set specific x-axis ticks at desired fault counts
        fault_counts = [10, 50, 100, 500, 1000]
        ax.set_xticks(fault_counts)
        ax.set_xticklabels([str(x) for x in fault_counts])

        # Set title - only show model name on top row
        if row == 0:
            ax.set_title(f"{display_name}", fontweight='bold', fontsize=24)

        # Y-axis label and formatter: YOLO values are mAP@50, others are accuracy %
        if model_name == "yolo":
            ax.set_ylabel("mAP@50", fontweight='bold')
        else:
            ax.set_ylabel("Accuracy (%)", fontweight='bold')

        # Add grid for better readability
        ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)

        # Rotate x-axis labels for better readability
        ax.tick_params(axis='x', rotation=45)

        # Make tick labels bold
        for tick in ax.get_xticklabels():
            tick.set_fontweight("bold")
        for tick in ax.get_yticklabels():
            tick.set_fontweight("bold")

# Add row labels on the left side
row_labels = ['Multiplication', 'Bit Flip']
for row, label in enumerate(row_labels):
    axes[row, 0].annotate(label, xy=(-0.4, 0.5), xycoords='axes fraction',
                          fontsize=30, fontweight='bold', rotation=90,
                          ha='center', va='center')

# Create a single legend at the top center
handles, labels = axes[0, 0].get_legend_handles_labels()
fig.legend(handles, labels, loc='upper center', bbox_to_anchor=(0.5, 1.02),
          ncol=4, framealpha=0.9, edgecolor='gray', fontsize=19)

# Add common X label
fig.supxlabel('Fault Count', fontsize=30, fontweight='bold', y=0.00)

plt.subplots_adjust(left=0.08, right=0.98, top=0.91, bottom=0.13, hspace=0.4, wspace=0.35)
plt.savefig("plots/eight_plots.png", dpi=300, bbox_inches='tight')
plt.savefig("plots/eight_plots.pdf", bbox_inches='tight')  # Also save as PDF for publications
print("Saved plots/eight_plots.png and plots/eight_plots.pdf")
